using HosteliteAPI.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HosteliteAPI.Dtos
{
    public class UserForDetailedDtos
    {
        /// <summary>
        /// The primary key: autogenerated value
        /// </summary>
        /// <returns></returns>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// The email field that holds a unique email address of every user
        /// </summary>
        /// <returns></returns>
        public string Email { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        public string Firstname { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        public string Lastname { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        public string Gender { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        public int Age { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        public DateTime DateJoined { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        public string PhotoUrl { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        public ICollection<PhotosForDetailedDto> Photos { get; set; }
    }
}
