// <auto-generated />
using System;
using HosteliteAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HosteliteAPI.Migrations
{
    /// <summary>
    /// database migration
    /// </summary>
    /// <returns></returns>
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191126140343_Initial")]
    partial class Initial
    {
        /// <summary>
        /// database migration
        /// </summary>
        /// <returns></returns>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HosteliteAPI.Models.Hostel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedHostel");

                    b.Property<string>("HostelAddress");

                    b.Property<string>("HostelDescription");

                    b.Property<string>("HostelLocation");

                    b.Property<string>("HostelName");

                    b.Property<int>("HostelNumberOfRooms");

                    b.Property<string>("HostelSlug");

                    b.Property<string>("HostelType");

                    b.Property<double>("RentPerRoom");

                    b.Property<bool>("VacantRoom");

                    b.HasKey("ID");

                    b.ToTable("Hostels");
                });

            modelBuilder.Entity("HosteliteAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
