using System; 
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HosteliteAPI.Models
{
    /// <summary>
    /// The user model abstraction that stores a user credentails
    /// </summary>
    /// <returns></returns>
    public class User
    {
        /// <summary>
        /// The primary key: autogenerated value
        /// </summary>
        /// <returns></returns>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// The email field that holds a unique email address of every user
        /// </summary>
        /// <returns></returns>
        public string Email { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        public byte[] PasswordHash { get; set; }

        /// <summary>
        /// The password salt field that holds a salt parameter used for transforming the user's password
        /// </summary>
        /// <returns></returns>
        public byte[] PasswordSalt { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        public string Firstname { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        public string Lastname { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        public string Gender { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        public DateTime DOB { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        /// 
        //[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime DateJoined { get; set; }

        public bool IsLandlord { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>
        ///
        public ICollection<Photo> Photos { get; set; }

        /// <summary>
        /// The password hash field that holds the hashed value of the user's password
        /// </summary>
        /// <returns></returns>

        //public ICollection<Hostel> hostels { get; set; }
        public User()
        {
            Photos = new Collection<Photo>();

            //hostels = new Collection<Hostel>();

            DateJoined = DateTime.Now;
        }
    }
}
